name: Distribute to Windows (NSIS)

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Push events to all tags

jobs:
  build-win:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '16.0' # Use the appropriate Visual Studio version, e.g., '16.0' for Visual Studio 2019

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - run: npm install
    
    - run: npm run build

    - run: Remove-Item -Path ./dist/win-unpacked/ -Recurse # This will make sure that Build Artifact doesn't take a lot of time to zip up the dist folder

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: win-nsis
        path: dist/
        publish: always
    - name: Extract version number
      run: |
        filename=$(find dist/ -name "skylinehosting-Setup-*.exe" -print -quit)
        regex="skylinehosting-Setup-(.*).exe"
        if [[ $filename =~ $regex ]]; then
          version=${BASH_REMATCH[1]}
          echo "Version number: $version"
          echo "::set-output name=version::$version"
        fi

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.tag_name }}
        release_name: ${{ steps.tag.outputs.tag_name }}
        draft: false
        prerelease: false
    
    - name: Publish Release
      uses: actions/create-release@v1.0.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.release_id }}
        tag_name: ${{ steps.tag.outputs.tag_name }}
        release_name: ${{ steps.tag.outputs.tag_name }}
        draft: false
        prerelease: false
        files: dist/skylinehosting-Setup-*.exe
