name: Distribute to Windows (NSIS)

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Push events to all tags

jobs:
  build-win:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '16.0' # Use the appropriate Visual Studio version, e.g., '16.0' for Visual Studio 2019

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-

    - run: npm install
    
    - run: npm run build

    - run: Remove-Item -Path ./dist/win-unpacked/ -Recurse # This will make sure that Build Artifact doesn't take a lot of time to zip up the dist folder

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: skylinehosting-Setup
        path: dist/skylinehosting-Setup-*.exe
        publish: always

    - name: Extract version number
      run: |
        filename=$(find dist/ -name "skylinehosting-Setup-*.exe" -print -quit)
        regex="skylinehosting-Setup-(.*).exe"
        if [[ $filename =~ $regex ]]; then
          version=${BASH_REMATCH[1]}
          echo "Version number: $version"
          echo "::set-output name=version::$version"
        fi

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1.12.0
      with:
        name: ${{ steps.tag.outputs.tag_name }}
        tag: ${{ steps.tag.outputs.tag_name }}
        draft: false
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Find artifact
      id: artifact
      run: |
        echo "##[set-output name=artifact_name]$(find . -name 'skylinehosting-Setup-v*.exe' -type f -printf '%f')"
  
    - uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: ${{ steps.artifact.outputs.artifact_name }}
        name: ${{ steps.tag.outputs.tag_name }}
        tag: ${{ steps.tag.outputs.tag_name }}